all:
	@cd libokey;make
	@cd keyGen;make
	@cd keyOpen;make
	@cd keyDel;make
	@cd keyInj;make
	@cd keyXtr;make
	@cd keyEnum;make
	@cd keyEncDec;make

clean:
	@cd libokey;make clean
	@cd keyGen;make clean
	@cd keyOpen;make clean
	@cd keyDel;make clean
	@cd keyInj;make clean
	@cd keyXtr;make clean
	@cd keyEnum;make clean
	@cd keyEncDec;make clean
